
---
- name: Download and Install Metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Drop in metricbeat
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable metricbeat
    command: metricbeat modules enable docker

  - name: Setup metricbeat
    command: metricbeat setup

  - name: Start metricbeat
    command: sudo service metricbeat start
